name: hitera_mobile
description: "HITERA - Personal Life Management Mobile App"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^6.0.1
  provider: ^6.1.2
  intl: ^0.20.2
  google_fonts: ^8.1.0
  fl_chart: ^1.2.0
  flutter_local_notifications: 21.0.0
  timezone: 0.11.0
  permission_handler: 12.0.1
  sqflite: ^2.3.0
  path: ^1.9.0
  connectivity_plus: ^7.1.1
  uuid: ^4.3.3
  flutter_timezone: ^5.0.2
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "image/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0a0a0f"
  adaptive_icon_foreground: "image/logo.png"

flutter:
  uses-material-design: true
  assets:
    - image/
    - .env

dependency_overrides:
  cli_util: 0.5.1
  json_annotation: 4.12.0
  matcher: 0.12.20
  meta: 1.18.2
  native_toolchain_c: 0.18.0
  package_info_plus: 10.1.0
  package_info_plus_platform_interface: 4.1.0
  test_api: 0.7.12
  vector_math: 2.3.0
  win32: 6.2.0
  xml: 7.0.1
